#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15


while getopts "d:c:r:a:e:i:lxvj" arg
do
	case $arg in
            i)  
                JF=$OPTARG 
                JF=`echo $OPTARG | gawk '{gsub(/[.]java$/,"",$0);print $0;}'`

                shift $(($OPTIND - 1))
                while [[ "$cmd" != "q" ]]
                do
                     print -n "figg/$JF >> ";read var;set -A arr $var;
                     cmd=${arr[0]};
	             case $cmd  in
                       f) JF=${arr[1]} ;;
                       e) figg -e $JF ;;
                       c) figg -c $JF ;;
                       d) figg -d $JF ;;
                       j) figg -j $JF ;;
                       r) figg -r $JF $1 $2 $3 $4 $5 $6;;
                       l) figg -l ;;
                       ls) figg -l ;;
                       reset)
                           rm -f classes/*.class  >/dev/null 2>&1
                           ;;
                       h) print "\n(f)ile (e)dit (c)ompile (d)ebug (r)un (l)ist (j)avadoc (h)elp\n" 
                          print "FILENAME IS "$JF"\n" 
                          javac -version
                          java -version
                          print "\n" 
                          ;;
	             esac
                done

               ;;
            c) JF=$OPTARG 
               rm -f tmp/$JF.lst >/dev/null 2>&1
               javac -Xlint:-rawtypes -cp classes -d classes src/$JF.java 2> tmp/$JF.lst
               if [ -s tmp/$JF.lst ]
               then
                    print "Listing"
                    vi src/$JF.java tmp/$JF.lst
                    # cat   tmp/$JF.lst
               else
                    print "OK"
               fi
               ;;
            d) JF=$OPTARG 
               shift $(($OPTIND - 1))
               vi tmp/$JF.lst src/$JF.java
               ;;
            x) 
               javac -cp classes -d classes src/*.java
               ;;
            r) JF=$OPTARG 
               shift $(($OPTIND - 1))
               rm -f $Tmp >/dev/null 2>&1
               java -cp classes $JF $1 $2 $3 $4 $5 $6 | tee $Tmp
               vim -O src/$JF.java $Tmp
               ;;
            a) JF=$OPTARG 
               shift $(($OPTIND - 1))
               javac -cp classes -d classes src/$JF.java
               java -cp classes $JF $1 $2 $3 $4 $5 $6
               ;;
            e) JF=$OPTARG 
               vi src/$JF.java
               ;;
            l) ls -l src
               ;;
            j) javadoc -d doc src/*.java
               xdg-open  "doc/index.html" >/dev/null 2>&1
               ;;
            v) java  -version
               ;;
	    *) exit 0 ;;
	esac
done


